name: CI
on: [push]
env:
  GO111MODULE: on

jobs:
  test:
    name: Signal test
    runs-on: ubuntu-latest
    container: 
      image: jlordiales/gha-signal-test:v1
      options: "--init"
    steps:
    - name: ps
      run: ps aux
    - name: Run
      run: /bin/main
